document:
  - "**/*.md"

agent:
  - "apm-sniffer/apm-sdk-plugin/**"
  - "apm-sniffer/optional-plugins/**"

plugin:
  - "apm-sniffer/apm-sdk-plugin/**"
  - "apm-sniffer/optional-plugins/**"

core feature:
  - "apm-sniffer/apm-agent-core/**"
  - "oap-server/server-core/**"
  - "oap-server/server-library/**"

docker:
  - "docker/**"

OAP-backend:
  - "oap-server/**"

UI:
  - "oap-server/server-query-plugin/**"
  - "skywalking-ui/**"

submodule update:
  - ".gitmodules"

CI settings:
  - "appveyor.yml"
  - "Jenkinsfile"
  - "Jenkinsfile-E2E"
  - ".github/**"
  - "tools/**"

test:
  - "test/**"