sudo: required

language: java

install:
  - jdk_switcher use oraclejdk8
  - ./mvnw clean install -Dmaven.test.skip=true --quiet
  - ./mvnw javadoc:javadoc -Dmaven.test.skip=true --quiet

after_success:
- ./mvnw clean -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID test jacoco:report coveralls:report --quiet
