sudo: required

language: java

install:
  - jdk_switcher use oraclejdk8
  - ./mvnw clean install --quiet
  - ./mvnw javadoc:javadoc -Dmaven.test.skip=true --quiet

after_success:
  - ./mvnw test jacoco:report coveralls:report --quiet
