sudo: required

services:
  - docker

language: java
install:
  - jdk_switcher use oraclejdk8
  - mvn clean install --quiet

after_success:
  - mvn clean test --quiet jacoco:report coveralls:report
  - bash ./travis/push_image.sh
