cluster:
  zookeeper:
    hostPort: localhost:2181
    sessionTimeout: 100000
#  redis:
#    host: localhost
#    port: 6379
agentstream:
  grpc:
    host: localhost
    port: 1000
  jetty:
    host: localhost
    port: 2000
    context_path: /
discovery:
  grpc: localhost
  port: 1000
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
storage:
  elasticsearch:
    cluster_name: CollectorDBCluster
    cluster_transport_sniffer: true
    cluster_nodes: 10.0.0.19:9300,10.0.0.6:9300


