apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      name: http
    - name: tcp
      port: {{ .Values.service.ports.transport }}
      targetPort: transport
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
