# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

expSuffix: service(['host'], Layer.OS_LINUX)
metricPrefix: meter_telegraf
metricsRules:

  # cpu
  - name: cpu_usage_guest_info
    exp: cpu_usage_guest
  - name: cpu_usage_guest_nice_info
    exp: cpu_usage_guest_nice
  - name: cpu_usage_idle_info
    exp: cpu_usage_idle
  - name: cpu_usage_iowait_info
    exp: cpu_usage_iowait
  - name: cpu_usage_nice_info
    exp: cpu_usage_nice
  - name: cpu_usage_softirq_info
    exp: cpu_usage_softirq
  - name: cpu_usage_steal_info
    exp: cpu_usage_steal
  - name: cpu_usage_system_info
    exp: cpu_usage_system * 100
  - name: cpu_usage_user_info
    exp: cpu_usage_user * 100

  # memory
  - name: mem_available_info
    exp: mem_available
  - name: mem_available_percent_info
    exp: mem_available_percent
  - name: mem_total_info
    exp: mem_total
  - name: mem_used_info
    exp: mem_used
  - name: mem_used_percent_info
    exp: mem_used_percent