cluster:
  standalone:
    url: jdbc:h2:~/memorydb
    user_name: sa
cache:
  guava:
queue:
  disruptor:
remote:
  gRPC:
    host: localhost
    port: 11800
naming:
  jetty:
    host: localhost
    port: 10800
    context_path: /
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
jetty_manager:
  jetty:
gRPC_manager:
  gRPC:
storage:
  h2:
    url: jdbc:h2:~/memorydb
    user_name: sa