cluster:
  h2:
    hostPort: localhost:2181
    sessionTimeout: 100000
naming:
  jetty:
    host: localhost
    port: 10800
    context_path: /
#agent_stream:
#  grpc:
#    host: localhost
#    port: 11800
#  jetty:
#    host: localhost
#    port: 12800
#    context_path: /
#  config:
#    buffer_offset_max_file_size: 10M
#    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
jetty_manager:
  jetty:
gRPC_manager:
  gRPC:
#collector_inside:
#  grpc:
#    host: localhost
#    port: 11800
storage:
  h2:
    url: jdbc:h2:~/memorydb
    user_name: sa
    password: